---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "postgresql-instance"
spec: 
  app: "postgresql"
  appCatalog: "local"
  roles: 
  - id: "pgsql-server"
    members: 1
    resources: 
      requests: 
        memory: "2Gi"
        cpu: "1"
      limits: 
        memory: "2Gi"
        cpu: "1"
